config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings, :only => [:index, :new, :create, :show] do
    collection do
      get 'aborted'
    end
  end
  namespace :admin do
    resources :bookings, :except => :show
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/terms' => 'pages#terms', as: :terms
  get 'pages/reps' => 'pages#reps', as: :reps, login_required: true
  get 'pages/rules' => 'pages#rules', as: :rules
  get 'pages/cleaning' => 'pages#cleaning', as: :cleaning
  get 'pages/about' => 'pages#about', as: :about
  get 'pages/price' => 'pages#price', as: :price

  root 'bookings#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user

  default_scope { where(status: "confirmed") }

  validates :user, presence: true
  validates :booking_date, presence: true
  validates :booking_date, uniqueness: {scope: :status}, if: :confirmed?
  validates :status, presence: true, inclusion: { in: %w(pending confirmed) }

  def self.all_future
    where('booking_date > ?', Date.today)
  end

  def self.all_this_month_and_forward
    where('booking_date > ?', Date.today.beginning_of_month)
  end

  # See https://stripe.com/docs/api/checkout/sessions/object
  def self.stripe_checkout_session_completed(stripe_obj)
    booking_id = stripe_obj.client_reference_id
    @booking = Booking.unscoped.find_by(id: booking_id, status: 'pending')
    @booking.update_attributes!(
      status: "confirmed",
      stripe_charge_id: stripe_obj.payment_intent
    )
  end

  # See https://stripe.com/docs/api/charges/object
  def self.stripe_charge_suceeded(stripe_obj)
    payment_intent_id = stripe_obj.payment_intent
    @booking = Booking.find_by(stripe_charge_id: payment_intent_id)

    billing_email = stripe_obj.billing_details.email
    @booking.user.update_attributes!(email: billing_email)
    UserMailer.booking_confirmation(@booking.user, @booking).deliver_now
  end

  def pending?
    status == "pending"
  end

  def confirmed?
    status == "confirmed"
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!
  before_action :set_booking, only: [:edit, :update, :destroy]
  authorize_resource
  before_action :load_all_users, only: [:new, :create, :edit, :update]

  # GET /admin/bookings
  # GET /admin/bookings.json
  def index
    @current_year = params['year'].try(:to_i) || Time.now.year
    @bookings = Booking.includes(:user).order(booking_date: :asc)
      .where(booking_date: Date.new(@current_year, 1, 1)..Date.new(@current_year, 12, 31))
  end

  # GET /admin/bookings/new
  def new
    @booking = Booking.new(:user_id => current_user.id)
  end

  # GET /admin/bookings/1/edit
  def edit
  end

  # POST /admin/bookings
  # POST /admin/bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to admin_bookings_url, notice: 'Bookingen er nu oprettet.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/bookings/1
  # PATCH/PUT /admin/bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to admin_bookings_url, notice: 'Bookingen er blevet opdateret.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/bookings/1
  # DELETE /admin/bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to admin_bookings_url, notice: 'Bookingen er nu slettet.' }
      format.json { head :no_content }
    end
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booking_date, :user_id, :description)
    end

    def require_admin!
      # TODO: Figure out how to this check and redirect properly
      redirect_to root_url, notice: 'Du skal være administrator for at tilgå denne del af systemet.' unless current_user.admin?
    end

    def load_all_users
      @all_users = User.all
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, :except => :index
  before_action :set_booking, only: [:show]
  authorize_resource

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all_this_month_and_forward
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking_date = params[:date].try(:to_date) rescue nil
    redirect_to bookings_path, notice: 'Vælg venligst den dato du ønsker at booke.' unless @booking_date.present?

    @booking = Booking.new(:booking_date => @booking_date)
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params.merge(status: 'pending'))

    # Make sure the booking belongs to the current user
    @booking.user = current_user

    # Only start payment process if booking is valid
    if @booking.valid?
      # Get the credit card details submitted by the form
      # token = params[:stripeToken]

      # Create the charge on Stripe's servers - this will charge the user's card
      #   begin
      #     charge = Stripe::Charge.create(
      #       :amount => BOOGIE_SETTINGS[:booking_fee],
      #       :currency => "DKK",
      #       :card => token,
      #       :description => "#{@booking.user.username} #{@booking.booking_date.to_s(:utc)}"
      #     )
      #     @booking.stripe_charge_id = charge.id
      #   rescue Stripe::CardError => e
      #     raise e # TEST
      #     charge = false
      #   end
      # end

      respond_to do |format|
        if @booking.save

          # Update the user's email with what they entered in the Stripe window
          # current_user.update_attribute(:email, charge.source['name']) if charge.source['name'].present?

          # Send confirmation email to the user
          # UserMailer.booking_confirmation(current_user, @booking).deliver

          @stripe_session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
              name: 'Booking af fælleslokalet',
              description: l(@booking.booking_date, format: BOOGIE_SETTINGS[:date_format]),
              amount: booking_fee_by_date(@booking.booking_date),
              currency: 'dkk',
              quantity: 1
            }],
            client_reference_id: @booking.id,
            success_url: booking_url(@booking),
            cancel_url: aborted_bookings_url
          )

          format.json { render json: { booking: @booking, stripe_session_id: @stripe_session.id } }
        else
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def booking_params
    params.require(:booking).permit(:booking_date)
  end
end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def for_each_future_month(month_count)

    now = Time.now
    year = now.year
    month = now.month

    month_count.times do
      yield(year, month)

      month += 1
      if month > 12
        year += 1
        month = 1
      end
    end
  end
end

app/views/admin/bookings/_form.html.erb
<%= form_for([:admin, @booking]) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation" class="info-box bg-danger text-danger">
      <h4><%= @booking.errors.count %> fejl forhindrede denne booking i at blive gemt:</h4>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :booking_date, 'Booking dato' %><br>
    <%= f.date_select :booking_date, {}, :class => 'input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :user_id, 'Bruger' %><br>
    <%= f.select :user_id, @all_users.collect { |user| [user.username, user.id] }, {}, :class => 'input-lg' %>
    <div class="help-text">Vælg din egen bruger hvis du booker på vegne af en forening til et fællesarrangement. Vælg kun en anden bruger hvis du booker på vegne af en beboer, og I sørger for betalingen uden om dette system.</div>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Beskrivelse' %><br>
    <%= f.text_field :description, :class => 'form-control' %>
    <div class="help-text">Hvis du booker til en foreningsaktivitet; angiv venligst aktiviteten her</div>
  </div>

  <%= f.submit 'Gem booking', :class => 'btn btn-default' %>
<% end %>

app/views/admin/bookings/edit.html.erb
<div class="page-header">
  <h1>Redigerer booking</h1>
</div>

<%= render 'form' %>

<%= link_to 'Tilbage', admin_bookings_path %>

app/views/admin/bookings/index.html.erb
<div class="page-header">
  <h1>Alle bookinger i <%= @current_year %></h1>
</div>

<p><%= link_to 'Opret gratis booking', new_admin_booking_path, class: 'btn btn-default' %></p>

<% if @bookings.empty? %>
  <p>Ingen bookinger endnu</p>
<% else %>
  <table class="table table-striped">
    <tr>
      <th>Dato</th>
      <th>Bruger</th>
      <th>Betaling</th>
      <th>Beskrivelse</th>
      <th>Handlinger</th>
    </tr>
    <% for booking in @bookings %>
      <tr>
        <td><%= l(booking.booking_date, format: BOOGIE_SETTINGS[:date_format]) %></td>
        <td><%= booking.user.username %></td>
        <td><%= link_to_if booking.stripe_charge_id.present?, booking.stripe_charge_id, "https://dashboard.stripe.com/payments/#{booking.stripe_charge_id}" %></td>
        <td><%= booking.description %></td>
        <td>
          <%= link_to 'Rediger', edit_admin_booking_path(booking) %> |
          <%= link_to 'Slet', admin_booking_path(booking), method: :delete, data: {confirm: "Er du sikker på du vil slette #{booking.user.username}'s booking #{l(booking.booking_date, format: BOOGIE_SETTINGS[:date_format])}?"} %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<ul class="pagination">
  <% for year in 2015..Time.now.next_year.year %>
    <li class="<%= year == @current_year ? 'active' : '' %>">
      <%= link_to year, admin_bookings_path(year: year) %>
    </li>
  <% end %>
</ul>

app/views/admin/bookings/new.html.erb
<div class="page-header">
  <h1>Opret ny booking</h1>
</div>

<%= render 'form' %>

<%= link_to 'Tilbage', admin_bookings_path %>