config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings, :only => [:index, :new, :create, :show] do
    collection do
      get 'aborted'
    end
  end
  namespace :admin do
    resources :bookings, :except => :show
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/terms' => 'pages#terms', as: :terms
  get 'pages/reps' => 'pages#reps', as: :reps, login_required: true
  get 'pages/rules' => 'pages#rules', as: :rules
  get 'pages/cleaning' => 'pages#cleaning', as: :cleaning
  get 'pages/about' => 'pages#about', as: :about
  get 'pages/price' => 'pages#price', as: :price

  root 'bookings#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user

  default_scope { where(status: "confirmed") }

  validates :user, presence: true
  validates :booking_date, presence: true
  validates :booking_date, uniqueness: {scope: :status}, if: :confirmed?
  validates :status, presence: true, inclusion: { in: %w(pending confirmed) }

  def self.all_future
    where('booking_date > ?', Date.today)
  end

  def self.all_this_month_and_forward
    where('booking_date > ?', Date.today.beginning_of_month)
  end

  # See https://stripe.com/docs/api/checkout/sessions/object
  def self.stripe_checkout_session_completed(stripe_obj)
    booking_id = stripe_obj.client_reference_id
    @booking = Booking.unscoped.find_by(id: booking_id, status: 'pending')
    @booking.update_attributes!(
      status: "confirmed",
      stripe_charge_id: stripe_obj.payment_intent
    )
  end

  # See https://stripe.com/docs/api/charges/object
  def self.stripe_charge_suceeded(stripe_obj)
    payment_intent_id = stripe_obj.payment_intent
    @booking = Booking.find_by(stripe_charge_id: payment_intent_id)

    billing_email = stripe_obj.billing_details.email
    @booking.user.update_attributes!(email: billing_email)
    UserMailer.booking_confirmation(@booking.user, @booking).deliver_now
  end

  def pending?
    status == "pending"
  end

  def confirmed?
    status == "confirmed"
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!
  before_action :set_booking, only: [:edit, :update, :destroy]
  authorize_resource
  before_action :load_all_users, only: [:new, :create, :edit, :update]

  # GET /admin/bookings
  # GET /admin/bookings.json
  def index
    @current_year = params['year'].try(:to_i) || Time.now.year
    @bookings = Booking.includes(:user).order(booking_date: :asc)
      .where(booking_date: Date.new(@current_year, 1, 1)..Date.new(@current_year, 12, 31))
  end

  # GET /admin/bookings/new
  def new
    @booking = Booking.new(:user_id => current_user.id)
  end

  # GET /admin/bookings/1/edit
  def edit
  end

  # POST /admin/bookings
  # POST /admin/bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to admin_bookings_url, notice: 'Bookingen er nu oprettet.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/bookings/1
  # PATCH/PUT /admin/bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to admin_bookings_url, notice: 'Bookingen er blevet opdateret.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/bookings/1
  # DELETE /admin/bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to admin_bookings_url, notice: 'Bookingen er nu slettet.' }
      format.json { head :no_content }
    end
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booking_date, :user_id, :description)
    end

    def require_admin!
      # TODO: Figure out how to this check and redirect properly
      redirect_to root_url, notice: 'Du skal være administrator for at tilgå denne del af systemet.' unless current_user.admin?
    end

    def load_all_users
      @all_users = User.all
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, :except => :index
  before_action :set_booking, only: [:show]
  authorize_resource

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all_this_month_and_forward
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking_date = params[:date].try(:to_date) rescue nil
    redirect_to bookings_path, notice: 'Vælg venligst den dato du ønsker at booke.' unless @booking_date.present?

    @booking = Booking.new(:booking_date => @booking_date)
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params.merge(status: 'pending'))

    # Make sure the booking belongs to the current user
    @booking.user = current_user

    # Only start payment process if booking is valid
    if @booking.valid?
      # Get the credit card details submitted by the form
      # token = params[:stripeToken]

      # Create the charge on Stripe's servers - this will charge the user's card
      #   begin
      #     charge = Stripe::Charge.create(
      #       :amount => BOOGIE_SETTINGS[:booking_fee],
      #       :currency => "DKK",
      #       :card => token,
      #       :description => "#{@booking.user.username} #{@booking.booking_date.to_s(:utc)}"
      #     )
      #     @booking.stripe_charge_id = charge.id
      #   rescue Stripe::CardError => e
      #     raise e # TEST
      #     charge = false
      #   end
      # end

      respond_to do |format|
        if @booking.save

          # Update the user's email with what they entered in the Stripe window
          # current_user.update_attribute(:email, charge.source['name']) if charge.source['name'].present?

          # Send confirmation email to the user
          # UserMailer.booking_confirmation(current_user, @booking).deliver

          @stripe_session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
              name: 'Booking af fælleslokalet',
              description: l(@booking.booking_date, format: BOOGIE_SETTINGS[:date_format]),
              amount: booking_fee_by_date(@booking.booking_date),
              currency: 'dkk',
              quantity: 1
            }],
            client_reference_id: @booking.id,
            success_url: booking_url(@booking),
            cancel_url: aborted_bookings_url
          )

          format.json { render json: { booking: @booking, stripe_session_id: @stripe_session.id } }
        else
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def booking_params
    params.require(:booking).permit(:booking_date)
  end
end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def for_each_future_month(month_count)

    now = Time.now
    year = now.year
    month = now.month

    month_count.times do
      yield(year, month)

      month += 1
      if month > 12
        year += 1
        month = 1
      end
    end
  end
end

app/views/bookings/aborted.html.erb
<div class="page-header">
  <h1>Din booking blev annulleret</h1>
</div>

<p>Du har afbrudt betalingen for din booking.</p>
<p><%= link_to 'Prøv igen', new_booking_path %></p>

app/views/bookings/index.html.erb
<h1>Book fællesrummet</h1>

<% for_each_future_month(7) do |year, month| %>
  <div class="booking-month">
    <h3><%= t('date.month_names')[month].titleize %> <%= year %></h3>
    <%= calendar_for(@bookings, :year => year, :month => month, :first_day_of_week => 1, :html => {:class => 'table table-bordered'}) do |t| %>
      <%= t.head(*t('date.day_names').rotate(1).map { |n| n.titleize.first(2) }) %>
      <%= t.day(:day_method => :booking_date) do |day, bookings| %>
        <% if day.month == month %>
          <% if day < Time.now %>
            <div class="past-date"><%= day.day %></div>
          <% elsif bookings.present? %>
            <div class="booked-date"
            <% if bookings.first.description.present? %>
              title="<%= bookings.first.description %>"
            <% end %>
            ><%= day.day %></div>
          <% else %>
            <div class="bookable-date">
              <%= link_to day.day, new_booking_path(:date => day.to_s(:utc)) %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="page-header">
  <h1>Bekræft booking</h1>
</div>

<p>Du er ved at booke fælleslokalet</p>
<p class="info-box bg-primary lead"><%= l(@booking.booking_date, format: BOOGIE_SETTINGS[:date_format]) %></p>
<p>
  Der bliver trukket <b><%= number_to_currency(booking_fee_by_date(@booking.booking_date)/100) %></b> fra dit betalingskort.
  Bookingen og betalingen er bindende og kan ikke annulleres eller laves om.
</p>

<p class="info-box bg-danger text-danger hidden" id="terms_not_accepted_error">Du skal acceptere betingelserne for leje for at fortsætte.</p>

<%= form_for @booking, html: { id: 'booking_form' } do |f| %>
  <%= f.hidden_field :booking_date %>
  <div class="checkbox">
    <label>
      <input type="checkbox" id="terms_accepted" value="v1" />
      Jeg accepterer <%= link_to 'betingelserne for leje', terms_path, target: '_new' %>
    </label>
  </div>

  <button type="button" class="btn btn-primary" id="start_payment_button">Fortsæt til betaling</button>
  <div class="three-quarters-loader hidden">
    Vent venligst ...
  </div>
<% end %>

<script src="https://js.stripe.com/v3/"></script>

<script>
  window.bootstrapData = {
    stripe: {
      key: '<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>',
      amount: '<%= booking_fee_by_date(@booking.booking_date) %>'
    },
    current_booking_date: '<%= params['date'] %>',
    current_user: <%=raw current_user.to_json %>
  }
</script>

app/views/bookings/show.html.erb
<div class="page-header">
  <h1>Kvittering for booking</h1>
</div>

<p>Du har nu booket fælleslokalet</p>
<p class="info-box bg-primary lead"><%= l(@booking.booking_date, format: BOOGIE_SETTINGS[:date_format]) %></p>
<p>Du skal selv aftale udlevering af nøgle med fællesrummets repræsentant i din forening.</p>
<p><%= link_to 'Se liste over repræsentanter', reps_path %></p>
<p>Du bedes inden du overtager rummet sætte dig ind i:</p>
<ul>
  <li><%= link_to 'Husorden', rules_path %></li>
  <li><%= link_to 'Rengøringsregler', cleaning_path %></li>
</ul>