config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings, :only => [:index, :new, :create, :show] do
    collection do
      get 'aborted'
    end
  end
  namespace :admin do
    resources :bookings, :except => :show
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/terms' => 'pages#terms', as: :terms
  get 'pages/reps' => 'pages#reps', as: :reps, login_required: true
  get 'pages/rules' => 'pages#rules', as: :rules
  get 'pages/cleaning' => 'pages#cleaning', as: :cleaning
  get 'pages/about' => 'pages#about', as: :about
  get 'pages/price' => 'pages#price', as: :price

  root 'bookings#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fællesrummet</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= yield :head %>
</head>
<body role="document">

  <!-- Fixed navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Fold navigation ind/ud</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SKRum</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(bookings_path) || current_page?(root_path) %>"><%= link_to 'Ny booking', bookings_path %></li>

          <li class="<%= 'active' if current_page?(rules_path) %>"><%= link_to 'Husorden -  skal læses', rules_path %></li>
          <li class="<%= 'active' if current_page?(cleaning_path) %>"><%= link_to 'Rengøring', cleaning_path %></li>
          <li class="<%= 'active' if current_page?(terms_path) %>"><%= link_to 'Betingelser', terms_path %></li>
          <li class="<%= 'active' if current_page?(price_path) %>"><%= link_to 'Pris', price_path %></li>
          <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to 'Om rummet', about_path %></li>

          <% if user_signed_in? %>
            <li class="<%= 'active' if current_page?(reps_path) %>"><%= link_to 'Repræsentanter', reps_path %></li>
          <% end %>

          <% if user_signed_in? && current_user.admin? %>
            <li class="<%= 'active' if current_page?(admin_bookings_path) %>"><%= link_to 'Administrer bookinger', admin_bookings_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
            <%= link_to('Log ud', destroy_user_session_path, :method => :delete) %>
            </li>
          <% else %>
            <li class="<%= 'active' if current_page?(new_user_session_path) %>">
            <%= link_to('Log ind', new_user_session_path)  %>
            </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <!-- Main container -->
  <div class="container" role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>